name: Deploy docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/pages.yml
    with:
      artifact-name: "docs"

  prepare:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
            name: "docs"
            path: "docs"
      - name: Check
        run: ls -R
      - name: Prepare for pages
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: "docs"
  deploy:
    needs: prepare
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v2.0.0
