name: Create docs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make docs
        run: |
          mkdir docs
          cd docs
          echo "<html><head><title>TEST</title></head><body><p>Hello world!</p></body></html>" > index.html
