# This is a basic workflow to help you get started with Actions

name: Test docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make docs
        run: |
          mkdir docs
          cd docs
          echo "<html><head>TEST</head><body><p>Hello world!</p></body></html>" > index.html
      - name: Prepare for pages
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: "docs"
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v2.0.0
